/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connectmysql;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ELCOT
 */
public class Book extends javax.swing.JFrame {
    
    private Connection connection;
    private DefaultTableModel tableModel;

    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
        connection=dbcon.getConnection();
        loadCategories();
    }
    
    private void loadCategories(){
        try{
            Statement statement=connection.createStatement();
            ResultSet resultset=statement.executeQuery("SELECT * from book");
            
            tableModel=(DefaultTableModel) table.getModel();
            tableModel.setRowCount(0);
            
            while(resultset.next()){
                int id=resultset.getInt("id");
                String an=resultset.getString("b_name");
                String adr=resultset.getString("category");
                String pho=resultset.getString("publisher");
                String a=resultset.getString("author");
                String c=resultset.getString("contents");
                String p=resultset.getString("pages");
                String e=resultset.getString("edition");
                
                tableModel.addRow(new Object[]{id,an,adr,pho,a,c,p,e});
            }
        }
        catch(SQLException e){
            jOptionPane.showMessageDialog(this,"Failed to load categories from the database.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b = new java.awt.TextField();
        c = new java.awt.TextField();
        n = new java.awt.TextField();
        e = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cat = new javax.swing.JComboBox<>();
        a = new javax.swing.JComboBox<>();
        p = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setText("Book Name");

        jLabel2.setText("Category");

        jLabel3.setText("Author");

        jLabel4.setText("Publisher");

        jLabel5.setText("Contents");

        jLabel6.setText("No of Pages");

        jLabel7.setText("Edition");

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        button1.setActionCommand("ADD");
        button1.setLabel("ADD");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setLabel("UPDATE");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setLabel("DELETE");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setLabel("CANCEL");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Book Name", "Category", "Author", "Publisher", "Contents", "No of Pages", "Edition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select an Option", "Programming", "Scripting", "Graphics", "Software", "Hardware" }));

        a.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select an Option", "Smith", "Henry", "Nicolas", "Jhonson", "Beverly", " " }));

        p.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select an Option", "xYz", "abc", "red gaint", "sun pictures" }));

        label1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label1.setText("Books");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cat, 0, 160, Short.MAX_VALUE)
                            .addComponent(a, 0, 1, Short.MAX_VALUE)
                            .addComponent(p, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(e, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        
        MainPage c6=new MainPage();
        this.hide();
        c6.setVisible(true);
    }//GEN-LAST:event_button4ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        
        String bo=b.getText();
        String ca = cat.getSelectedItem().toString();
        String ad = a.getSelectedItem().toString();
        String ph = p.getSelectedItem().toString();
        String co=c.getText();
        String no=n.getText();
        String ed=e.getText();
        
         
        if(bo.isEmpty()) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter Book Name", "Error", jOptionPane.ERROR_MESSAGE);
} else if(!bo.matches("[a-zA-Z]+")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter alphabets only", "Error", jOptionPane.ERROR_MESSAGE);
} 
        if(ca.equals("Please Select an Option")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please select an option", "Error", jOptionPane.ERROR_MESSAGE);
} else {
    // Option is valid
}
        if(ad.equals("Please Select an Option")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please select an option", "Error", jOptionPane.ERROR_MESSAGE);
} else {
    // Option is valid
}
        if(ph.equals("Please Select an Option")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please select an option", "Error", jOptionPane.ERROR_MESSAGE);
} else {
    // Option is valid
}
 if(co.isEmpty()) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter Contents", "Error", jOptionPane.ERROR_MESSAGE);
} else if(!co.matches("[a-zA-Z]+")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter alphabets only", "Error", jOptionPane.ERROR_MESSAGE);
}       
    if(no.isEmpty()) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter Number of Pages", "Error", jOptionPane.ERROR_MESSAGE);
} else if(!no.matches("[0-9]+")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter Numberss only", "Error", jOptionPane.ERROR_MESSAGE);
}    
    if(ed.isEmpty()) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter Edition", "Error", jOptionPane.ERROR_MESSAGE);
} else if(!ed.matches("[0-9]+")) {
    // Display an error message
    jOptionPane.showMessageDialog(null, "Please enter Numbers only", "Error", jOptionPane.ERROR_MESSAGE);
}
    else
{
    
    

         try{
            
            String query="INSERT INTO book (b_name,category,author,publisher,contents,pages,edition) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement statement=connection.prepareStatement(query);
            statement.setString(1,bo);
            statement.setString(2,ca);
            statement.setString(3,ad);
            statement.setString(4,ph);
            statement.setString(5,co);
            statement.setString(6,no);
            statement.setString(7,ed);
            int k=statement.executeUpdate();
            loadCategories();
            
            
            if(k==1)
            {
                jOptionPane.showMessageDialog(null,"Book Added Successfully...");
    
        b.setText("");
        cat.setSelectedItem("Please Select an Option");
        a.setSelectedItem("Please Select an Option");
        p.setSelectedItem("Please Select an Option");
        
        c.setText("");
        n.setText("");
       e.setText("");
                
                
                
            }
            else
            {
                jOptionPane.showMessageDialog(null,"Failed to insert Book...");
            }
//            statement.close();
//            connection.close();
        }
         
     
    catch(SQLException ex)
    {
        ex.printStackTrace();
    }
    
    
    //System.exit(0);
}
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        
        int selrow=table.getSelectedRow();
      
      if(selrow!=-1){
          int catid=(int) tableModel.getValueAt(selrow, 0);
          String bo=b.getText();
        String ca = cat.getSelectedItem().toString();
        String ad = a.getSelectedItem().toString();
        String ph = p.getSelectedItem().toString();
        String co=c.getText();
        String no=n.getText();
        String ed=e.getText();
          
          if(!bo.isEmpty()){
              try{
                  PreparedStatement statement=connection.prepareStatement("UPDATE book SET b_name=?,category=?,author=?,publisher=?,contents=?,pages=?,edition=? WHERE id=?");
                  statement.setString(1,bo);
            statement.setString(2,ca);
            statement.setString(3,ad);
            statement.setString(4,ph);
            statement.setString(5,co);
            statement.setString(6,no);
            statement.setString(7,ed);
                  statement.setInt(8, catid);
                  statement.executeUpdate();
                  
                  loadCategories();
                  b.setText("");
        cat.setSelectedItem("Please Select an Option");
        a.setSelectedItem("Please Select an Option");
        p.setSelectedItem("Please Select an Option");
        
        c.setText("");
        n.setText("");
       e.setText("");
                  
              }
              catch(SQLException e){
                  jOptionPane.showMessageDialog(this,"Failed to update the Book.");
              }
          }
          else{
              jOptionPane.showMessageDialog(null, "Please enter Book name", "Error", jOptionPane.ERROR_MESSAGE);
          }
      }
      else{
          jOptionPane.showMessageDialog(this,"Please select the Book to update.");
      }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        
        button3.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                int ser=table.getSelectedRow();
                if(ser!=-1){
                    int con=jOptionPane.showConfirmDialog(Book.this,"Are you sure you want to delete this Book?","Confirm Delete",jOptionPane.YES_NO_OPTION);
                    if(con==jOptionPane.YES_OPTION){
                        String id=table.getValueAt(ser,0).toString();
                        try{
                            String sql="DELETE FROM book WHERE id=?";
                            PreparedStatement statement=connection.prepareStatement(sql);
                            statement.setString(1,id);
                            statement.executeUpdate();
                            statement.close();
                            
                            loadCategories();
                        }
                        catch(SQLException ex){
                            jOptionPane.showMessageDialog(Book.this,"Failed to delete the Book.");
                        }
                    }
                }
                else{
                    jOptionPane.showMessageDialog(Book.this,"Please select a Book to delete.");
                }
            }
        });
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> a;
    private java.awt.TextField b;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.TextField c;
    private javax.swing.JComboBox<String> cat;
    private java.awt.TextField e;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.TextField n;
    private javax.swing.JComboBox<String> p;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
